# ============================================================
# kitty.conf — opsi bila memakai kitty (--kitty)
# Palette Catppuccin Mocha + background semi-transparan
# ============================================================
font_family JetBrainsMono Nerd Font
font_size 11.0

# Semi-transparan (blur di-handle picom)
background_opacity 0.85
dynamic_background_opacity yes

# Warna (Catppuccin Mocha)
background #1e1e2e
foreground #cdd6f4
cursor #f5c2e7

color0 #45475a
color8 #585b70
color1 #f38ba8
color9 #f38ba8
color2 #a6e3a1
color10 #a6e3a1
color3 #f9e2af
color11 #f9e2af
color4 #89b4fa
color12 #89b4fa
color5 #f5c2e7
color13 #f5c2e7
color6 #94e2d5
color14 #94e2d5
color7 #bac2de
color15 #a6adc8

# Estetika
hide_window_decorations titlebar-only
window_padding_width 8
tab_bar_style powerline
background_tint 0.0